import type { AnalysisScene } from '../model/types';

export const druckerPragerSlopeScene: AnalysisScene = {
  gravity: { enabled: true, x: 0, y: -0.000390625 },
  nodes: [
    { id: 'node-1', x: 0, y: 0 },
    { id: 'node-2', x: 80, y: 0 },
    { id: 'node-3', x: 160, y: 0 },
    { id: 'node-4', x: 240, y: 0 },
    { id: 'node-5', x: 0, y: 80 },
    { id: 'node-6', x: 80, y: 80 },
    { id: 'node-7', x: 160, y: 80 },
    { id: 'node-8', x: 240, y: 80 },
    { id: 'node-9', x: 0, y: 160 },
    { id: 'node-10', x: 80, y: 160 },
    { id: 'node-11', x: 160, y: 120 },
  ],
  elements: [
    { id: 'element-1', nodeIds: ['node-1', 'node-2', 'node-6'], materialId: 'material-1' },
    { id: 'element-2', nodeIds: ['node-1', 'node-6', 'node-5'], materialId: 'material-1' },
    { id: 'element-3', nodeIds: ['node-2', 'node-3', 'node-7'], materialId: 'material-1' },
    { id: 'element-4', nodeIds: ['node-2', 'node-7', 'node-6'], materialId: 'material-1' },
    { id: 'element-5', nodeIds: ['node-3', 'node-4', 'node-8'], materialId: 'material-1' },
    { id: 'element-6', nodeIds: ['node-3', 'node-8', 'node-7'], materialId: 'material-1' },
    { id: 'element-7', nodeIds: ['node-5', 'node-6', 'node-10'], materialId: 'material-1' },
    { id: 'element-8', nodeIds: ['node-5', 'node-10', 'node-9'], materialId: 'material-1' },
    { id: 'element-9', nodeIds: ['node-6', 'node-7', 'node-11'], materialId: 'material-1' },
    { id: 'element-10', nodeIds: ['node-6', 'node-11', 'node-10'], materialId: 'material-1' },
    { id: 'element-11', nodeIds: ['node-7', 'node-8', 'node-11'], materialId: 'material-1' },
  ],
  supports: [
    { id: 'support-1', nodeId: 'node-1', direction: 'x' },
    { id: 'support-2', nodeId: 'node-1', direction: 'y' },
    { id: 'support-3', nodeId: 'node-2', direction: 'y' },
    { id: 'support-4', nodeId: 'node-3', direction: 'y' },
    { id: 'support-5', nodeId: 'node-4', direction: 'y' },
    { id: 'support-6', nodeId: 'node-5', direction: 'x' },
    { id: 'support-7', nodeId: 'node-9', direction: 'x' },
  ],
  loads: [],
  materials: [
    {
      id: 'material-1',
      name: 'Material 1',
      kind: 'drucker-prager-plane-strain',
      youngModulus: 40_000,
      poissonRatio: 0.3,
      density: 1,
      beta: 0.08,
      mu: 2,
      exponent: 1,
      loadSteps: 20,
      maxIterations: 50,
      tolerance: 1e-8,
    },
  ],
};